solidjs/solidhack-submissions

README.md

Repository: https://github.com/Exelord/solid-proxies

Submit Solid Proxies

---

README.md

Hey. I'm glad to show my project bloki. This is editor for content creation. 
In short this is notion + miro with automatic grid layout.
Main goal is to implement simple editor that will not be restricted to one axis, but will help to place content evenly.
You can create text blocks, they will be automatically adjusted to your text size. However, initially you can create blocks only in main grid that is placed in middle of screen.
You can move it by snapping with middle mouse or by dragging icon with six dots.
In the future I'm planning to implement automatic layout, so when you will try to move block, all blocks below and grouped blocks will free space for desired place. Inline text editing, commands, nested documents, attaching drawing to text and blocks and more. I wrote a roadmap: …

Submission for Best Student Project Award: Bloki app 

---

README.md

This PR adds [Solar Forms](https://github.com/kajetansw/solar-forms) to SolidHack 2022 competition in Best Ecosystem Utility category.
- [Stackblitz demo](https://stackblitz.com/edit/solid-vite-km8l2n?file=src/index.tsx)

Submission for Best Ecosystem Utility: Solar Forms

---

README.md

[`classy-solid`](https://github.com/lume/classy-solid) - Solid.js reactivity patterns for classes, and class components.
The `classy-solid` package gives you a `@signal` decorator to make reactive class properties, a `@component` decorator for using classes as Solid components, and some other APIs to simplify usage of reactive patterns in classes.
Demo: https://first-person-shooter.meteorapp.com

Ecosystem utility: `classy-solid`

---

README.md

"Magic Pixels" is a Web3 Dapp where you can gamble to get Pixels, use them to create pixel art and mint them as NFTs.
Repository: https://github.com/maxdavidwow/magic-pixels
Demo: https://magic-pixels.surge.sh/

Submission for: magic-pixels

---

README.md

Thanks for your consideration!

Submission for Best Ecosystem Utility: Solid UI - reactive primitives and hooks for building accessible, composable UI components

---

README.md

https://github.com/fwouts/previewjs-solid-plugin

Submission: SolidJS plugin for Preview.js

---

README.md

You know Melon-Solid is a juicy pick! 🍈🍉💦

---

README.md

repo at https://github.com/Bedrock-Layouts/Solid-Bedrock
Docs/Example at solid.bedrock-layout.dev

Solid-Bedrock Hackathon submission

---

README.md

Repository: https://github.com/TiagoCavalcante/solidjs-div-100vh
Example app: https://solidjs-div-100vh.vercel.app/

Submission for Best Ecosystem Utility: solidjs-div-100vh

---

README.md

Repository : https://github.com/harshmangalam/hydrogen-solidjs-client
Live Demo : https://hydrogen-solid.vercel.app/
Video Demo : https://www.youtube.com/watch?v=9ItTT385NJM

Submission for Hydrogen:Best Student Project Award

---

README.md

Learn and make music interactively.
Repository: https://github.com/eguneys/solsido
App: https://lasolsido.org/

Submission for: Lasolsido.org

---

README.md

Simple and secure to-do list, for people who want a bit more privacy. No need to sign up or log in, everything is encrypted and stored locally.
[Github repository](https://github.com/Nojus0/encrypted-todo-list)
[Deployed](https://encryptedtodos.netlify.app/)
*M* Mute audio
*N* Next scene
*B* Previous scene

Submission for: Encrypted to-do list

---

README.md

Repository: https://github.com/specialdoom/solid-rev-kit
Docs: https://specialdoom.github.io/solid-rev-kit-docs

Submission for: RevKit UI

---

README.md

Repository/docs: https://github.com/everweij/solid-boundaries
Example: https://7j26ix.sse.codesandbox.io/

Submission for: solid-boundaries

---

README.md

Repository: https://github.com/DanielHZhang/zutto
Demo: see releases page for compiled binaries: https://github.com/DanielHZhang/zutto/releases

Submission for Best App: `Zutto`

---

README.md

Repo: https://github.com/CompendiumDevTools/library
Demo: https://github.com/CompendiumDevTools/devtools#previews

Submission: `Compendium DevTools`

---

README.md

A little credential manager based on the [PwdHash](https://crypto.stanford.edu/PwdHash/) idea.
Users can generate a different password for each site they sign up to, based on their master password.
[App](https://app.rehash.one/)

Submission for: rehash.one

---

README.md

repo: https://github.com/yellowsink/solid-reactor
demo: https://youtu.be/Yt-_b3h0SjE

Add submission: Solid Reactor

---

README.md

https://github.com/LUMECraft/first-person-shooter
A first-person shooter game foundation made with [LUME](https://lume.io/), [Solid.js](https://solidjs.com/) (and libs), and [Meteor](https://www.meteor.com/).
LUMECraft's `first-person-shooter` aims to be an open-source starting point for
FPS games written declaratively using LUME's 3D HTML elements with Solid.js
templating and reactivity, and realtime multiplayer connectivity powered by
Meteor.js. Eventually it will be skinnable, moddable, and more.
Demo: https://first-person-shooter.meteorapp.com

App: LUMECraft `first-person-shooter`

---

README.md

Repository: https://github.com/gstatem/gstatem/tree/main/packages/solid-gstatem
Docs: https://gstatem.netlify.app/?path=/docs/solid-basic-usage--page

Submission for: solid-gstatem

---

README.md

Repository: https://github.com/swordev/suid
Docs: https://suid.io

Submission for: SUID - Material UI

---

README.md

Repository: https://github.com/Aslemammad/solid-spring
Docs: [Readme](https://github.com/aslemammad/solid-spring#solid-spring)

Submission for: Solid-spring

---

README.md

Repository: <https://github.com/tjjfvi/solid-native>
Example App: <https://solid-native.t6.fyi/>

Submission for Best Ecosystem Utility: Solid Native

---

.github/workflows/on_pr.yml
.idea/.gitignore
.idea/modules.xml
.idea/solidhack-submissions.iml
.idea/vcs.xml
README.md

Submission for blitz, the next-gen state management library for solid-js.
Github: https://github.com/dimensionhq/blitz
NpmJS: https://www.npmjs.com/package/@dimensionhq/blitz
Website: https://blitz.dimension.dev

Submission for Blitz, the modern state management library for Solid-JS.

---

README.md

This PR adds [Solid data grid demo](https://github.com/esveo/solid-data-grid-demo) within the Best App category.
Originally this was intended to become a full fledged library, but I ran out of time and so a demo has to suffice :D

Add solid data grid demo

---

README.md

Repository: https://github.com/mokshit06/solid-table
Docs: https://solidjs-table.vercel.app

Submission for: solid table

---

README.md

https://github.com/frozar/gdrive-tree
Simple viewer of your google drive work space.
https://gdrive-tree.vercel.app/

GDrive Tree - Best App by frozar

---

README.md

Live demo: https://sailwind.dev
Video demo: https://twitter.com/lawrencecchen/status/1507712718412812291
Repo: https://github.com/lawrencecchen/sailwind

Submission for Best Student Project Award: Sailwind

---

README.md

**Repository** (Solid specific): https://github.com/StudioLambda/TurboSolid
**Repository 2** (Framework agnostic): https://github.com/StudioLambda/TurboQuery
**Documentation** (Solid specific): https://erik.cat/post/turbo-solid-lightweight-asynchronous-data-management-for-solid
**Documentation 2** (Framework agnostic): https://erik.cat/post/turbo-query-lightweight-asynchronous-data-management
**Demo Playground** (Solid specific): https://turbo-solid.erik.cat/

Added `turbo-solid`

---

README.md

SolidGraph lets you build applications with SolidJs and WunderGraph.
github: https://github.com/verdavaine/solidgraph
demo: https://solidgraph.ovh/

Submission for Best Ecosystem Utility: SolidGraph

---

README.md

solid-material-ui port using css variables for theming.
Repository: https://github.com/skclusive/solid-material-ui
Docs: https://skclusive.github.io/solid-material-ui/docs/
Docs YouTube: https://www.youtube.com/watch?v=A7cZpWEBhl0
Dashboard: https://skclusive.github.io/solid-material-ui/dashboard/
Dashboard YouTube: https://www.youtube.com/watch?v=uw2cofhMypg

Submission for Best Ecosystem Utility: solid-material-ui

---

README.md

Repository: https://github.com/dylanclaywell/get-productive
App: [getproductive.app](https://getproductive.app/)

Submission for Best App: getPRODUCTIVE

---

README.md

Project page: https://github.com/rrjanbiah/react2solid
Demo: https://rrjanbiah.github.io/react2solid/

react2solid for Best Ecosystem Utility Award

---

README.md

Here is the repo: https://github.com/Perivel/solidus-js
Demo: https://github.com/Perivel/solidus-demo

SolidusJS: Plug and Play SSR for SolidJS

---

README.md

Website to find SolidJS jobs and SolidJS developers
Project page: https://github.com/rrjanbiah/solidjs-jobs
Demo: https://rrjanbiah.github.io/solidjs-jobs/

solidjs-jobs for Best Ecosystem Utility Award

---

README.md

Reverts solidjs/solidhack-submissions#60

"GDrive Tree - Best App by frozar"
